[package]
name = "xbf_rs"
version = "0.1.0"
edition = "2021"
description = "A Rust implementation of the XBF format."
license = "MIT OR Apache-2.0"

[dependencies]
byteorder = "1"
indexmap = "2.0.0"

[dev-dependencies]
anyhow = "1.0"

[features]
default = ["xbf_threadsafe"]
xbf_threadsafe = []

[[example]]
name = "server"
required-features = ["xbf_threadsafe"]
