/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xdl_kt

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun testFunc(): String {
        return "fucking xdl"
    }
}
